[build]
publish = "."

[functions]
directory = "functions"

[build.environment]
NODE_VERSION = "18"

[[headers]]
for = "/*"
[headers.values]
cache-control = "max-age=0, no-cache, no-store, must-revalidate"
X-Frame-Options = "DENY"

Remove the line:
base = "project"